### PR TITLE
Handle no plans saved in DB (endpoint call failed)

### LINKED ISSUE #166: ErrorException: Warning: count(): Parameter must be an array or an object that implements Countable
Sentry Issue: [WUBTITLE-WORDPRESS-11](https://sentry.io/organizations/ctmobi/issues/1777379566/?referrer=github_integration)

```
ErrorException: Warning: count(): Parameter must be an array or an object that implements Countable
  File "/wp-content/plugins/Wubtitle/includes/Dashboard/Settings.php", line 320, in Wubtitle\Dashboard\Settings::init_settings_field
    if ( get_option( 'wubtitle_plan_rank' ) < count( $plans ) - 1 ) {
```

### LINKED ISSUE #167: ErrorException: Warning: Invalid argument supplied for foreach()
Sentry Issue: [WUBTITLE-WORDPRESS-12](https://sentry.io/organizations/ctmobi/issues/1777442397/?referrer=github_integration)

```
ErrorException: Warning: Invalid argument supplied for foreach()
  File "/wp-content/plugins/Wubtitle/includes/Dashboard/Templates/payment_template.php", line 54, in include
    foreach ( $plan['features'] as $key => $feature ) :
  File "/wp-content/plugins/Wubtitle/includes/Dashboard/PaymentTemplate.php", line 64, in Wubtitle\Dashboard\PaymentTemplate::load_payment_template
    include 'Templates/payment_template.php';
...
(1 additional frame(s) were not displayed)
```

### LINKED ISSUE #170: PHP Warning in dashboard
#### Steps to reproduce the issue

1.  Activate the plugin for the firt time (or clear wubtitle_all_plans value from db)
2.  Go to Wubtitle settings page.
3.  You'll notice two errors about count() function.

#### What happened
While the plugin activation the endpoint call failed, so the wubtitle_all_plans has no value.

### PR DESCRIPTION
**Pull request by nicola-palermo**
### All Submissions:

*   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
*   [x] Does your code has proper inline documentation? 

### Changes proposed in this Pull Request:

Handled no value in db and displayed message.

Closes #170  .
Closes #166 .
Closes #167  .

### Other information:

*   [x] Have you added an explanation of what your changes do and why you'd like us to include them?
*   [ ] Have you written new tests for your changes, as applicable?
*   [ ] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

Handled no value in db for wubtitle_all_plans.
Displayed message.

### CODE REVIEW

**Comment by GiuseppeIuculano** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ includes/Dashboard/Settings.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=5849944&bid=19151205)

File: includes/Dashboard/Settings.php [hunk 1]
```diff
@@ -381,11 +379,18 @@ public function input_field( $args ) {
 	 */
 	public function upgrade_button( $args ) {
 		?>
-		<button id="buy-license-button" class="button-primary" >
+		<button id="buy-license-button" class="button-primary <?php echo esc_html( $args['disabled'] ); ?>">
```
Comment (HyprCoder) [inline includes/Dashboard/Settings.php:382]: Use the esc_attr function here

File: includes/Dashboard/Settings.php [hunk 2]
```diff
@@ -290,15 +291,8 @@ private function remote_request( $license_key ) {
...
-		$validation['error'] = 'xxx';
-		if ( 200 === $status && ! $validation['verified'] ) {
-			$validation['error'] = $retrieved['data']['errorType'];
-		} elseif ( 500 <= $status && 600 > $status ) {
-			$validation['error'] = '5xx';
-		} elseif ( 400 <= $status && 500 > $status ) {
-			$validation['error'] = '4xx';
-		}
+		$helpers             = new Helpers();
+		$validation['error'] = $helpers->validation_error( $status, $validation['verified'], $retrieved['data']['errorType'] );
```
Comment (HyprCoder) [inline includes/Dashboard/Settings.php:295]: What is the value of this property if there are no errors? The name of this function should be changed with something more descriptive

Comment (nicola-palermo) [reply includes/Dashboard/Settings.php:295]: It will always be an "error" but two types:
- Error calling remote endpoint
- The data received from endpoint will be EXPIRED or INVALID

The messages are handled on line 233 if statement.

Should I change the function name anyway?
