### PR TITLE
Fix register rest route wordpress5.5

### LINKED ISSUE #305: ErrorException: User Notice: register_rest_route was called <strong>incorrectly</strong>. The REST API route defi...
Sentry Issue: [WUBTITLE-WORDPRESS-3H](https://sentry.io/organizations/ctmobi/issues/1855947150/?referrer=github_integration)

```
ErrorException: User Notice: register_rest_route was called <strong>incorrectly</strong>. The REST API route definition for <code>wubtitle/v1/store-subtitle</code> is missing the required <code>permission_callback</code> argument. For REST API routes that are intended to be public, use <code>__return_true</code> as the permission callback. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 5.5.0.)
  File "/wp-content/plugins/wubtitle/includes/Api/ApiStoreSubtitle.php", line 41, in Wubtitle\Api\ApiStoreSubtitle::register_store_subtitle_route
    'callback' => array( $this, 'auth_and_get_subtitle' ),
...
(7 additional frame(s) were not displayed)
```

### LINKED ISSUE #306: ErrorException: User Notice: register_rest_route was called <strong>incorrectly</strong>. The REST API route defi...
Sentry Issue: [WUBTITLE-WORDPRESS-3G](https://sentry.io/organizations/ctmobi/issues/1855947149/?referrer=github_integration)

```
ErrorException: User Notice: register_rest_route was called <strong>incorrectly</strong>. The REST API route definition for <code>wubtitle/v1/reset-user</code> is missing the required <code>permission_callback</code> argument. For REST API routes that are intended to be public, use <code>__return_true</code> as the permission callback. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 5.5.0.)
  File "/wp-content/plugins/wubtitle/includes/Api/ApiLicenseValidation.php", line 57, in Wubtitle\Api\ApiLicenseValidation::register_reset_invalid_license_route
    'callback' => array( $this, 'get_init_data' ),
...
(7 additional frame(s) were not displayed)
```

### LINKED ISSUE #307: ErrorException: User Notice: register_rest_route was called <strong>incorrectly</strong>. The REST API route defi...
Sentry Issue: [WUBTITLE-WORDPRESS-3F](https://sentry.io/organizations/ctmobi/issues/1855947144/?referrer=github_integration)

```
ErrorException: User Notice: register_rest_route was called <strong>incorrectly</strong>. The REST API route definition for <code>wubtitle/v1/job-list</code> is missing the required <code>permission_callback</code> argument. For REST API routes that are intended to be public, use <code>__return_true</code> as the permission callback. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 5.5.0.)
  File "/wp-content/plugins/wubtitle/includes/Api/ApiLicenseValidation.php", line 41, in Wubtitle\Api\ApiLicenseValidation::register_license_validation_route
    'callback' => array( $this, 'auth_and_get_job_list' ),
...
(7 additional frame(s) were not displayed)
```

### LINKED ISSUE #308: ErrorException: User Notice: register_rest_route was called <strong>incorrectly</strong>. The REST API route defi...
Sentry Issue: [WUBTITLE-WORDPRESS-3B](https://sentry.io/organizations/ctmobi/issues/1855947128/?referrer=github_integration)

```
ErrorException: User Notice: register_rest_route was called <strong>incorrectly</strong>. The REST API route definition for <code>wubtitle/v1/auth-plan</code> is missing the required <code>permission_callback</code> argument. For REST API routes that are intended to be public, use <code>__return_true</code> as the permission callback. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 5.5.0.)
  File "/wp-content/plugins/wubtitle/includes/Api/ApiAuthUpgradePlan.php", line 40, in Wubtitle\Api\ApiAuthUpgradePlan::register_auth_plan_route
    'callback' => array( $this, 'auth_and_get_plan' ),
...
(7 additional frame(s) were not displayed)
```

### LINKED ISSUE #310: ErrorException: User Notice: register_rest_route was called <strong>incorrectly</strong>. The REST API route defi...
Sentry Issue: [WUBTITLE-WORDPRESS-3D](https://sentry.io/organizations/ctmobi/issues/1855947139/?referrer=github_integration)

```
ErrorException: User Notice: register_rest_route was called <strong>incorrectly</strong>. The REST API route definition for <code>wubtitle/v1/error-jobs</code> is missing the required <code>permission_callback</code> argument. For REST API routes that are intended to be public, use <code>__return_true</code> as the permission callback. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 5.5.0.)
  File "/wp-content/plugins/wubtitle/includes/Api/ApiStoreSubtitle.php", line 201, in Wubtitle\Api\ApiStoreSubtitle::register_error_jobs_route
    'callback' => array( $this, 'get_jobs_failed' ),
...
(7 additional frame(s) were not displayed)
```

### LINKED ISSUE #311: ErrorException: User Notice: register_rest_route was called <strong>incorrectly</strong>. The REST API route defi...
Sentry Issue: [WUBTITLE-WORDPRESS-3C](https://sentry.io/organizations/ctmobi/issues/1855947132/?referrer=github_integration)

```
ErrorException: User Notice: register_rest_route was called <strong>incorrectly</strong>. The REST API route definition for <code>wubtitle/v1/reactivate-plan</code> is missing the required <code>permission_callback</code> argument. For REST API routes that are intended to be public, use <code>__return_true</code> as the permission callback. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 5.5.0.)
  File "/wp-content/plugins/wubtitle/includes/Api/ApiAuthUpgradePlan.php", line 55, in Wubtitle\Api\ApiAuthUpgradePlan::register_reactivate_plan_route
    'callback' => array( $this, 'reactivate_plan' ),
...
(7 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by cpalessio96**
### All Submissions:

*   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
*   [x] Does your code has proper inline documentation? 

### Changes proposed in this Pull Request:
add permission callback to register rest route

Closes #305  .
Closes #306  .
Closes #307  .
Closes #308  .
Closes #310  .
Closes #311  .

### CODE REVIEW

**Review by SalvoCozzubo — DISMISSED** [review]

File: includes/Api/ApiStoreSubtitle.php [hunk 1]
```diff
@@ -37,8 +37,11 @@ public function register_store_subtitle_route() {
 			'wubtitle/v1',
 			'/store-subtitle',
 			array(
-				'methods'  => 'POST',
-				'callback' => array( $this, 'auth_and_get_subtitle' ),
+				'methods'             => 'POST',
+				'callback'            => array( $this, 'auth_and_get_subtitle' ),
+				'permission_callback' => function() {
+					return current_user_can( 'manage_options' );
+				},
```
Comment (HyprCoder) [inline includes/Api/ApiStoreSubtitle.php]: Is this endpoint get called when a new job is started? the permission used in permission_callback is for administrator only. Should this operation be called also for other roles? (such as authors and editors)

File: includes/Api/ApiStoreSubtitle.php [hunk 2]
```diff
@@ -197,8 +200,11 @@ public function register_error_jobs_route() {
 			'wubtitle/v1',
 			'/error-jobs',
 			array(
-				'methods'  => 'POST',
-				'callback' => array( $this, 'get_jobs_failed' ),
+				'methods'             => 'POST',
+				'callback'            => array( $this, 'get_jobs_failed' ),
+				'permission_callback' => function() {
+					return current_user_can( 'manage_options' );
+				},
```
Comment (HyprCoder) [inline includes/Api/ApiStoreSubtitle.php]: Same as upper comment.

**Review by HyprCoder — CHANGES_REQUESTED** [review]

**Review by HyprCoder — APPROVED** [review]
