### PR TITLE
check isset for params

### LINKED ISSUE #347: ErrorException: Notice: Trying to access array offset on value of type null
Sentry Issue: [WUBTITLE-WORDPRESS-3M](https://sentry.io/organizations/ctmobi/issues/1868155425/?referrer=github_integration)

```
ErrorException: Notice: Trying to access array offset on value of type null
  File "/wp-content/plugins/Wubtitle-Wordpress-Plugin/includes/Api/ApiLicenseValidation.php", line 72, in Wubtitle\Api\ApiLicenseValidation::Wubtitle\Api\{closure}
    $token            = $headers['token'][0];
  File "/wp-blog-header.php", line 16, in require
    wp();
  File "/index.php", line 17
    require __DIR__ . '/wp-blog-header.php';
...
(7 additional frame(s) were not displayed)
```

### LINKED ISSUE #348: ErrorException: Notice: Undefined index: jobId
Sentry Issue: [WUBTITLE-WORDPRESS-3N](https://sentry.io/organizations/ctmobi/issues/1868270748/?referrer=github_integration)

```
ErrorException: Notice: Undefined index: jobId
  File "/wp-content/plugins/Wubtitle-Wordpress-Plugin/includes/Api/ApiStoreSubtitle.php", line 195, in Wubtitle\Api\ApiStoreSubtitle::get_jobs_failed
    $job_id   = $params['jobId'];
  File "/wp-blog-header.php", line 16, in require
    wp();
  File "/index.php", line 17
    require __DIR__ . '/wp-blog-header.php';
...
(7 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by cpalessio96**
### All Submissions:

*   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
*   [x] Does your code has proper inline documentation? 

### Changes proposed in this Pull Request:
Fix bug reported by sentry
Closes #347 
Closes #348

### CODE REVIEW

**Comment by GiuseppeIuculano** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- includes/Api/ApiLicenseValidation.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=6097088&bid=19961034)

File: includes/Api/ApiLicenseValidation.php [hunk 1]
```diff
@@ -75,6 +75,7 @@ public function register_reset_invalid_license_route() {
 					}
 					wp_cache_delete( 'wubtitle_token', 'options' );
 					wp_cache_delete( 'wubtitle_token_time', 'options' );
+					$token            = isset( $headers['token'][0] ) ? $headers['token'][0] : '';
```
Comment (HyprCoder) [inline includes/Api/ApiLicenseValidation.php]:
```suggestion
					$token            = $headers['token'][0] ?? '';
```
prova questa sintassi

File: includes/Api/ApiStoreSubtitle.php [hunk 2]
```diff
@@ -192,7 +192,7 @@ public function register_error_jobs_route() {
 	 */
 	public function get_jobs_failed( $request ) {
 		$params   = $request->get_param( 'data' );
-		$job_id   = $params['jobId'];
+		$job_id   = isset( $params['jobId'] ) ? $params['jobId'] : '';
```
Comment (HyprCoder) [inline includes/Api/ApiStoreSubtitle.php]: stessa cosa qui

**Review by HyprCoder — CHANGES_REQUESTED** [review]

**Review by HyprCoder — APPROVED** [review]
